"""New domain models

Revision ID: 2244123344e5
Revises: 595f35b4d1e0
Create Date: 2025-09-10 14:22:08.891379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2244123344e5"
down_revision: Union[str, Sequence[str], None] = "595f35b4d1e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_project_filename", "documents", ["project_id", "filename"]
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "uploader_id")
    op.create_unique_constraint(None, "projects", ["name"])
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.create_unique_constraint("uq_users_name", "users", ["name"])
    op.create_unique_constraint("uq_users_name_email", "users", ["name", "email"])
    op.create_unique_constraint(None, "users", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint("uq_users_name_email", "users", type_="unique")
    op.drop_constraint("uq_users_name", "users", type_="unique")
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_constraint(None, "projects", type_="unique")
    op.add_column(
        "documents", sa.Column("uploader_id", sa.VARCHAR(length=36), nullable=False)
    )
    op.create_foreign_key(None, "documents", "users", ["uploader_id"], ["id"])
    op.drop_constraint("uq_project_filename", "documents", type_="unique")
    # ### end Alembic commands ###
