"""Postgres branch init

Revision ID: bb1bfc4b7fde
Revises: 68231f3fa1ac
Create Date: 2025-09-11 11:52:56.752119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = 'bb1bfc4b7fde'
down_revision: Union[str, Sequence[str], None] = '68231f3fa1ac'
branch_labels: Union[str, Sequence[str], None] = ('postgres',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'email', name='uq_users_name_email'),
    sa.UniqueConstraint('name', name='uq_users_name')
    )
    op.create_table('projects',
    sa.Column('id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('owner_id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('project_id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'filename', name='uq_project_filename')
    )
    op.create_table('project_memberships',
    sa.Column('project_id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('user_id', app.adapters.repositories.sqlalchemy.types.UUID(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_memberships')
    op.drop_table('documents')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
